openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /api/v1/categories:
    get:
      summary: list categories
      tags:
        - Categories
      responses:
        '200':
          description: successful
