# Dockerfile.backend

FROM ruby:3.1-alpine

RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    tzdata \
    yarn

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

RUN yarn install

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]