// Mock data for testing the admin modules

export const mockLeads = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao@empresa.com',
    phone: '(11) 99999-8888',
    company: 'Empresa A',
    source: 'site',
    status: 'novo',
    score: 75,
    createdAt: '2025-04-01',
    lastContact: '2025-04-05',
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria@tech.com',
    phone: '(21) 98888-7777',
    company: 'Tech Solutions',
    source: 'redes',
    status: 'contatado',
    score: 85,
    createdAt: '2025-04-02',
    lastContact: '2025-04-06',
  },
  {
    id: '3',
    name: 'Pedro Alves',
    email: 'pedro@innovate.com',
    phone: '(31) 97777-6666',
    company: 'Innovate Ltda',
    source: 'indicacao',
    status: 'qualificado',
    score: 92,
    createdAt: '2025-04-03',
    lastContact: '2025-04-07',
  },
  {
    id: '4',
    name: 'Ana Costa',
    email: 'ana@energia.com',
    phone: '(41) 96666-5555',
    company: 'Energia Verde',
    source: 'webinar',
    status: 'convertido',
    score: 95,
    createdAt: '2025-04-04',
    lastContact: '2025-04-08',
  },
  {
    id: '5',
    name: 'Carlos Oliveira',
    email: 'carlos@solar.com',
    phone: '(51) 95555-4444',
    company: 'Solar Tech',
    source: 'site',
    status: 'descartado',
    score: 30,
    createdAt: '2025-04-05',
    lastContact: '2025-04-09',
  },
];

export const mockMembers = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao@empresa.com',
    plan: 'pro',
    status: 'ativo',
    subscriptionStart: '2025-01-01',
    subscriptionEnd: '2026-01-01',
    paymentStatus: 'pago',
    profileUrl: 'https://example.com/profile/1',
    createdAt: '2025-01-01',
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria@tech.com',
    plan: 'enterprise',
    status: 'ativo',
    subscriptionStart: '2025-02-01',
    subscriptionEnd: '2026-02-01',
    paymentStatus: 'pago',
    profileUrl: 'https://example.com/profile/2',
    createdAt: '2025-02-01',
  },
  {
    id: '3',
    name: 'Pedro Alves',
    email: 'pedro@innovate.com',
    plan: 'basico',
    status: 'inativo',
    subscriptionStart: '2025-03-01',
    subscriptionEnd: '2026-03-01',
    paymentStatus: 'pendente',
    profileUrl: 'https://example.com/profile/3',
    createdAt: '2025-03-01',
  },
  {
    id: '4',
    name: 'Ana Costa',
    email: 'ana@energia.com',
    plan: 'pro',
    status: 'suspenso',
    subscriptionStart: '2025-04-01',
    subscriptionEnd: '2026-04-01',
    paymentStatus: 'atrasado',
    profileUrl: 'https://example.com/profile/4',
    createdAt: '2025-04-01',
  },
  {
    id: '5',
    name: 'Carlos Oliveira',
    email: 'carlos@solar.com',
    plan: 'enterprise',
    status: 'expirado',
    subscriptionStart: '2024-01-01',
    subscriptionEnd: '2025-01-01',
    paymentStatus: 'pago',
    profileUrl: 'https://example.com/profile/5',
    createdAt: '2024-01-01',
  },
];

export const mockSponsored = [
  {
    id: '1',
    name: 'SolarTech Solutions',
    description: 'Empresa líder em soluções de energia solar',
    website: 'https://solartech.com',
    tier: 'ouro',
    status: 'ativo',
    startDate: '2025-01-01',
    endDate: '2026-01-01',
    contactEmail: 'contato@solartech.com',
    contactPhone: '(11) 99999-8888',
    createdAt: '2025-01-01',
  },
  {
    id: '2',
    name: 'EcoEnergy Brasil',
    description: 'Soluções sustentáveis para empresas',
    website: 'https://ecoenergy.com.br',
    tier: 'diamante',
    status: 'ativo',
    startDate: '2025-02-01',
    endDate: '2026-02-01',
    contactEmail: 'contato@ecoenergy.com.br',
    contactPhone: '(21) 98888-7777',
    createdAt: '2025-02-01',
  },
  {
    id: '3',
    name: 'Green Power Solutions',
    description: 'Inovação em energia renovável',
    website: 'https://greenpower.com',
    tier: 'prata',
    status: 'pausado',
    startDate: '2025-03-01',
    endDate: '2026-03-01',
    contactEmail: 'contato@greenpower.com',
    contactPhone: '(31) 97777-6666',
    createdAt: '2025-03-01',
  },
  {
    id: '4',
    name: 'Solar Innovations LLC',
    description: 'Tecnologia de ponta em energia solar',
    website: 'https://solarinnovations.com.br',
    tier: 'bronze',
    status: 'encerrado',
    startDate: '2024-01-01',
    endDate: '2025-01-01',
    contactEmail: 'contato@solarinnovations.com.br',
    contactPhone: '(41) 96666-5555',
    createdAt: '2024-01-01',
  },
  {
    id: '5',
    name: 'Renewable Energy Corp',
    description: 'Energia limpa para todos',
    website: 'https://renewable.com.br',
    tier: 'ouro',
    status: 'ativo',
    startDate: '2025-04-01',
    endDate: '2026-04-01',
    contactEmail: 'contato@renewable.com.br',
    contactPhone: '(51) 95555-4444',
    createdAt: '2025-04-01',
  },
];

export const mockAccess = [
  {
    id: '1',
    userId: 'user1',
    productId: 'product1',
    role: 'admin',
    expiresAt: '2026-01-01',
    isActive: true,
    userName: 'João Silva',
    productName: 'SolarFinder Pro',
    createdAt: '2025-01-01',
  },
  {
    id: '2',
    userId: 'user2',
    productId: 'product2',
    role: 'editor',
    expiresAt: '2026-02-01',
    isActive: true,
    userName: 'Maria Santos',
    productName: 'SolarFinder Enterprise',
    createdAt: '2025-02-01',
  },
  {
    id: '3',
    userId: 'user3',
    productId: 'product3',
    role: 'leitor',
    expiresAt: '2025-12-31',
    isActive: false,
    userName: 'Pedro Alves',
    productName: 'SolarFinder Basic',
    createdAt: '2025-03-01',
  },
  {
    id: '4',
    userId: 'user4',
    productId: 'product4',
    role: 'admin',
    expiresAt: '2026-03-01',
    isActive: true,
    userName: 'Ana Costa',
    productName: 'SolarFinder Advanced',
    createdAt: '2025-04-01',
  },
  {
    id: '5',
    userId: 'user5',
    productId: 'product5',
    role: 'editor',
    expiresAt: '2025-11-30',
    isActive: false,
    userName: 'Carlos Oliveira',
    productName: 'SolarFinder Standard',
    createdAt: '2025-05-01',
  },
];

export const mockArticles = [
  {
    id: '1',
    title: 'Guia Completo para Energia Solar Residencial',
    content: 'Este artigo aborda todos os aspectos importantes da instalação de energia solar em residências...',
    author: 'João Silva',
    category: 'Guia',
    status: 'publicado',
    views: 1250,
    createdAt: '2025-04-01',
    updatedAt: '2025-04-05',
  },
  {
    id: '2',
    title: 'Como Escolher os Melhores Painéis Solares',
    content: 'A escolha dos painéis solares certos pode fazer uma grande diferença na eficiência do seu sistema...',
    author: 'Maria Santos',
    category: 'Dicas',
    status: 'publicado',
    views: 980,
    createdAt: '2025-04-02',
    updatedAt: '2025-04-06',
  },
  {
    id: '3',
    title: 'Benefícios Fiscais da Energia Solar no Brasil',
    content: 'Conheça os incentivos fiscais disponíveis para quem investe em energia solar...',
    author: 'Pedro Alves',
    category: 'Legislação',
    status: 'rascunho',
    views: 0,
    createdAt: '2025-04-03',
    updatedAt: '2025-04-03',
  },
  {
    id: '4',
    title: 'Manutenção de Sistemas Fotovoltaicos',
    content: 'Dicas essenciais para manter seu sistema solar funcionando perfeitamente...',
    author: 'Ana Costa',
    category: 'Manutenção',
    status: 'publicado',
    views: 750,
    createdAt: '2025-04-04',
    updatedAt: '2025-04-08',
  },
  {
    id: '5',
    title: 'Evolução da Tecnologia Solar',
    content: 'Como a tecnologia solar evoluiu nos últimos anos e o que esperar para o futuro...',
    author: 'Carlos Oliveira',
    category: 'Tecnologia',
    status: 'arquivado',
    views: 2100,
    createdAt: '2025-04-05',
    updatedAt: '2025-04-09',
  },
];